repos:
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.20
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
    additional_dependencies: [flake8-mypy]
